server:
  port: 10000

# spring 配置
spring:
  application:
    name: springcloud-consumer-feign

# eureka 配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: springcloud-consumer-feign-10000
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/

# feign hystrix 开启客户端降级
feign:
  hystrix:
    enabled: true

# eureka 上 provider 的实例名称
request:
  provider-server: SPRINGCLOUD-PROVIDER-SERVER
  sidecar-server: SPRINGCLOUD-SIDECAR-SERVER
