server:
  port: 10000

# spring 配置
spring:
  application:
    name: springcloud-consumer-feign

# eureka 配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: springcloud-consumer-feign-10000
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/


request:
  provider-server: SPRINGCLOUD-PROVIDER-SERVER