server:
  port: 9000

# spring 配置
spring:
  application:
    name: springcloud-consumer

# eureka 配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: springcloud-consumer-9000
  client:
    register-with-eureka: false  # 消费者向 eureka 不需要注册
    service-url:
      defaultZone: http://localhost:7000/eureka/
