server:
  port: 8000


# mybatis 配置
mybatis:
  type-aliases-package: cn.xyf.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
# config-location: classpath:mybatis/mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true


# spring 配置
spring:
  application:
    name: springcloud-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sc_db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 12345678