server.port: 28000

# spring cloud 配置
spring:
  application:
    name: springcloud-stream-consumer
  cloud:
    stream:
      bindings:
        input:
          destination: exchange1
          binder: rabbit1
          content-type: application/type
          group: group1
        msg_input:
          destination: mqtopic1
          binder: kafka1
          group: groupA
      default-binder: kafka1
      binders:
        rabbit1:
          type: rabbit
        kafka1:
          type: kafka

  rabbitmq:
    host: rabbitmq-server.hsb.cn
    port: 5672
    username: admin
    password: 12345678

  kafka:
    bootstrap-servers:
      - kafka-server.hsb.cn:9092 #kafka服务地址
#    consumer:
#      group-id: groupA

# eureka 配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: springcloud-stream-consumer-28000
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/